import { testConfig } from "./utilities"

export const defaultConfig: testConfig = {
    TBname: "wot-test-bench",
    http: {
        port: 8980,
        allowSelfSigned: true,
    },
    coap: {
        port: 5683,
    },
    SchemaLocation: "Resources/InteractionSchemas/",
    TestReportsLocation: "Reports/",
    TestDataLocation: "Resources/fake-data.json",
    TimeBetweenRequests: 500,
    ActionTimeout: 4000,
    Scenarios: 2,
    Repetitions: 1,
    EventAndObservePOptions: {
        Asynchronous: {
            MaxAmountRecvData: 2,
            MsListen: 400,
            MsSubscribeTimeout: 400,
        },
        Synchronous: {
            isEnabled: true,
            MaxAmountRecvData: 5,
            MsListen: 5000,
            MsSubscribeTimeout: 1000,
        },
    },
    credentials: {},
}

export const usernames = ["node-wot", "root", "admin", "test", "guest", "info", "adm", "user", "administrator", "pi", "sysadmin"]

export const usernames_short = ["node-wot", "admin", "test", "user"]

export const passwords = [
    "isgreat!",
    "123456",
    "password",
    "12345678",
    "qwerty",
    "123456789",
    "12345",
    "1234",
    "111111",
    "1234567",
    "dragon",
    "123123",
    "baseball",
    "abc123",
    "football",
    "monkey",
    "letmein",
    "696969",
    "shadow",
    "master",
    "666666",
    "qwertyuiop",
    "123321",
    "mustang",
    "1234567890",
    "michael",
    "654321",
    "pussy",
    "superman",
    "1qaz2wsx",
    "7777777",
    "fuckyou",
    "121212",
    "000000",
    "qazwsx",
    "123qwe",
    "killer",
    "trustno1",
    "jordan",
    "jennifer",
    "zxcvbnm",
    "asdfgh",
    "hunter",
    "buster",
    "soccer",
    "harley",
    "batman",
    "andrew",
    "tigger",
    "sunshine",
    "iloveyou",
    "fuckme",
    "2000",
    "charlie",
    "robert",
    "thomas",
    "hockey",
    "ranger",
    "daniel",
    "starwars",
    "klaster",
    "112233",
    "george",
    "asshole",
    "computer",
    "michelle",
    "jessica",
    "pepper",
    "1111",
    "zxcvbn",
    "555555",
    "11111111",
    "131313",
    "freedom",
    "777777",
    "hello",
    "pass",
    "fuck",
    "maggie",
    "159753",
    "aaaaaa",
    "ginger",
    "princess",
    "joshua",
    "cheese",
    "amanda",
    "summer",
    "love",
    "ashley",
    "6969",
    "nicole",
    "chelsea",
    "biteme",
    "matthew",
    "access",
    "yankees",
    "987654321",
    "dallas",
    "austin",
    "thunder",
    "taylor",
    "matrix",
    "minecraft",
]

export const passwords_short = ["123456", "password", "123123", "hello", "isgreat!"]
